<?php
$config['mysql_server']="localhost";
$config['mysql_user']="root";
$config['mysql_password']="root";
$config['mysql_table']="jabberfriends";
$config['languages']=array('de','en');
$config['class']=array('startpage','members','portal','wiki');
$config['method']=array('index',
                        'publickey',
                        'user_details',
                        'register',
                        'login',
                        'logout',
                        'options',
                        'changedetails',
                        'changetags',
                        'tag',
                        'members',
                        'search',
                        'wiki',
                        'wiki_version',
                        'editwiki',
                        'news',
                        'singlenews',
                        'writenews',
                        'portal',
                        'cite',
                        'add_cite',
                        'changepw');
$config['url']='http://www.jabberfriends.local/';
?>
